### ISSUE TITLE
error: use of undeclared identifier 'shrinker_rwsem'

### ISSUE THREAD

**Issue by aikooo7** [projects-nexus/nexus_kernel_xiaomi_sm8250#4]
When compiling the kernel with the default config it works fine, when I edit to make it able to run with docker I get:

```
  CC      mm/vmscan.o
../mm/vmscan.c:196:14: error: use of undeclared identifier 'shrinker_rwsem'
  196 |         down_write(&shrinker_rwsem);
      |                     ^
../mm/vmscan.c:213:12: error: use of undeclared identifier 'shrinker_rwsem'
  213 |         up_write(&shrinker_rwsem);
      |                   ^
../mm/vmscan.c:223:14: error: use of undeclared identifier 'shrinker_rwsem'
  223 |         down_write(&shrinker_rwsem);
      |                     ^
../mm/vmscan.c:225:12: error: use of undeclared identifier 'shrinker_rwsem'
  225 |         up_write(&shrinker_rwsem);
      |                   ^
../mm/vmscan.c:595:26: error: use of undeclared identifier 'shrinker_rwsem'
  595 |         if (!down_read_trylock(&shrinker_rwsem))
      |                                 ^
../mm/vmscan.c:645:27: error: use of undeclared identifier 'shrinker_rwsem'
  645 |                 if (rwsem_is_contended(&shrinker_rwsem)) {
      |                                         ^
../mm/vmscan.c:651:11: error: use of undeclared identifier 'shrinker_rwsem'
  651 |         up_read(&shrinker_rwsem);
      |                  ^
7 errors generated.
```

I just added the missing config, didn't change anything on the kernel, perhaps it is because of apparmor?

**Comment by NotZeetaa** [comment]
which branch are u using?

**Comment by aikooo7** [comment]
> which branch are u using?

a14-rebase, specific commit:

https://github.com/projects-nexus/nexus_kernel_xiaomi_sm8250/commit/2eda037c9d9b0c4eec3b76345bdf1eba2050633a

**Comment by NotZeetaa** [comment]
@aikooo7 Are you using my build script without any modifications?

**Comment by aikooo7** [comment]
> @aikooo7 Are you using my build script without any modifications?

I just removed the telegram part and added the options that I needed to the defconfig part where you merge all the configs.

**Comment by aikooo7** [comment]
Any updates? If you need I can give you all the files I changed

**Comment by NotZeetaa** [comment]
@aikooo7 You disable simple low memory killer

**Comment by aikooo7** [comment]
> @aikooo7 You disable simple low memory killer

I dont think so, do you want my config?

**Comment by aikooo7** [comment]
Do you think disabling the security options might help?

**Comment by aikooo7** [comment]
Any updates?

**Comment by aikooo7** [comment]
> @aikooo7 You disable simple low memory killer

Hey sorry for misunderstanding your message, disabling it indeed fixed the issue in that file but the same error appears in other files.

**Comment by aikooo7** [comment]
What I said was wrong, to fix the issue I added ``DECLARE_RWSEM(shrinker_rwsem);`` to  ``mm/vmscan.c``, then it worked, including with simple memory killer turned on.
